### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by alex-0xFF** [dancing-elf/teamcity-telegram-plugin#1]
Writing an issue as asked)
It will be great to support http proxy with authentication.

**Comment by dancing-elf** [comment]
Ok. I will try to do it at this weekend. Thank you for your feedback.

**Comment by dancing-elf** [comment]
Proxy support added. New release is available at https://plugins.jetbrains.com/plugin/9249?pr=teamcity.
I hope that no new bugs were added :)
