### ISSUE TITLE
No support for new bots in telegram (with Float id values)

### ISSUE THREAD

**Issue by karpyzin** [dancing-elf/teamcity-telegram-plugin#11]
I get error after test connection in TC:
_Can't send test message to Telegram:
Expected an int but was 5293000000 at line 1 column 37 path $.result.id_

Some months ago telegram migrated from Int to Float values in field 'id'. 
Id of new bots more than 2147483647

**Comment by plex61** [comment]
How to fix it?

**Comment by dancing-elf** [comment]
There is pr for this: https://github.com/dancing-elf/teamcity-telegram-plugin/pull/12
I think I will upload to jb new version on this or next week after some testing.

**Comment by dancing-elf** [comment]
Should be fixed
