### ISSUE TITLE
Weird group chat id

### ISSUE THREAD

**Issue by igrizzli** [dancing-elf/teamcity-telegram-plugin#3]
I tried to add chat bot to the group.

```
Hello! You chat id is '-176904772'.
If you want to receive notifications about Teamcity events please add this chat id in your Teamcity settings
```

It's weird that chat id is negative.
I tried to use it but it not work.

**Comment by dancing-elf** [comment]
As I can understand Telegram use negative chat id for groups and positive chat id for persons. So negative chat id should work for groups. I will try to test plugin with Telegram group on this week. If this don't work when it's a bug :(

**Comment by dancing-elf** [comment]
Sorry for big delay. I tested plugin with Teamcity 2017.1.2 and looks like it works for groups. Negative number is normal id for Telegram groups, it can be saved, messages are visible in group chat. Right now I can't reproduce any problem with group. What should I do?
