### ISSUE TITLE
Cannot create users after enabling plugin

### ISSUE THREAD

**Issue by soosap** [dancing-elf/teamcity-telegram-plugin#5]
There seems to quite a problem w/ using this plugin. I cannot add new users to my TeamCity account. When trying to do so I get the following error:

`notificator_telegram_telegram-chat-id:Chat id should be a number`

For the admin user I was able to set the telegram-chat-id. But for new users it is not clear how to set this id before the user is even created. This is a bug, right?

**Comment by dancing-elf** [comment]
Yes, it's sounds like a bug. But this problem has already been corrected in current release (linked issue https://github.com/dancing-elf/teamcity-telegram-plugin/issues/2).
Can't reproduce with TeamCity 2017.1.2.
So I need more information about you environment to reproduce this problem.

**Comment by soosap** [comment]
Ok yes you are right, problem is resolved :)
